#Start
#run  mysql first
#docker-compose -f jbpm-full-mysql.yml up --build -d
#docker-compose -f jbpm-full-mysql.yml down
#Bajar mysql
#docker-compose -f mysql.yml down

#Linux: $ ./standalone.sh &
#
#Windows: > standalone.bat
#
#Stop
#Linux: $ ./jboss-cli.sh --connect command=:shutdown
#
#Windows: > jboss-cli.bat --connect command=:shutdown
#
#Restart
#Linux: $ ./jboss-cli.sh --connect command=:reload
#
#Windows: > jboss-cli.bat --connect command=:reload
#- ./repo/wb_git:/opt/jboss/wildfly/bin/.niogit:Z

version: '3'
services:
  jbpm:
  #   image: jboss/jbpm-server-full:7.25.0.Final
    image: jboss/jbpm-server-full
    container_name: jbpm_connect_mysql
    #build: .
    environment:
      JBPM_DB_DRIVER: mysql
      JBPM_DB_HOST: 172.16.238.11
      JBPM_DB_PORT: 3306
      JBPM_DB_NAME: jbpm
      JBPM_DB_USER: jbpm
      JBPM_DB_PASSWORD: jbpm
      KIE_SERVER_ID: saymon_jbpm_id
    ports:
    - 8180:8080
    - 8001:8001
    volumes:
    - ./repo:/repo
    - ./repo/wb_git:/opt/jboss/wildfly/bin/.niogit:Z
    - ./repo/jboss:/opt/jboss/.m2/repository
networks:
  default:
    external:
      name: jbpm_docker_app_net


