package com.saymon.surveynps;
import com.saymon.surveynps.*;


rule "set as PROMOTOR" ruleflow-group "npsrules"
no-loop
when $p : ObjectNPS(nps >= 9)
then
     modify($p){
         setPromotor(true);
     }
end


rule "set as Neutro" ruleflow-group "npsrules"
no-loop
when $p : ObjectNPS(nps >= 7 && nps < 9)
then
     modify($p){
         setNeutro(true);
     }
end

rule "set as Detractor" ruleflow-group "npsrules"
no-loop
when $p : ObjectNPS(nps < 7)
then
     modify($p){
         setDetractor(true);
     }
end

