package uft.chapter02;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomMessage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomMessage() {
    }
    
    private String message;

	private long senderId;

	public CustomMessage(long senderId, String message) {
		this.senderId = senderId;
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	public long getSenderId() {
		return senderId;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public void setSenderId(long senderId) {
		this.senderId = senderId;
	}


}