package uft.chapter02;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HelloService implements java.io.Serializable {
	private static final HelloService INSTANCE = new HelloService();
	public static HelloService getInstance() {
		return INSTANCE;
	}
	public void sayHello(String name) {
		System.out.println("Hello " + name);
	}
}
