package uft.chapter02;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   //@org.kie.api.definition.type.Label(value = "Edad")
   private int age;
   //@org.kie.api.definition.type.Label(value = "Nombre")
   private java.lang.String name;

   public Person()
   {
   }

   public int getAge()
   {
      return this.age;
   }

   public void setAge(int age)
   {
      this.age = age;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Person(int age, java.lang.String name)
   {
      this.age = age;
      this.name = name;
   }

}