package com.saymon.surveynps;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ObjectNPS implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "OBJECTNPS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "OBJECTNPS_ID_GENERATOR", sequenceName = "OBJECTNPS_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Promotor")
	private java.lang.Boolean promotor;

	@org.kie.api.definition.type.Label("Detractor")
	private java.lang.Boolean detractor;

	@org.kie.api.definition.type.Label("Neutro")
	private java.lang.Boolean neutro;

	@org.kie.api.definition.type.Label(value = "Nps")
	private java.lang.Integer nps;

	public ObjectNPS() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean getPromotor() {
		return this.promotor;
	}

	public void setPromotor(java.lang.Boolean promotor) {
		this.promotor = promotor;
	}

	public java.lang.Boolean getDetractor() {
		return this.detractor;
	}

	public void setDetractor(java.lang.Boolean detractor) {
		this.detractor = detractor;
	}

	public java.lang.Boolean getNeutro() {
		return this.neutro;
	}

	public void setNeutro(java.lang.Boolean neutro) {
		this.neutro = neutro;
	}

	public java.lang.Integer getNps() {
		return this.nps;
	}

	public void setNps(java.lang.Integer nps) {
		this.nps = nps;
	}

	public ObjectNPS(java.lang.Long id, java.lang.Boolean promotor,
			java.lang.Boolean detractor, java.lang.Boolean neutro,
			java.lang.Integer nps) {
		this.id = id;
		this.promotor = promotor;
		this.detractor = detractor;
		this.neutro = neutro;
		this.nps = nps;
	}

}